resources:
  repositories:
  - repository: AnsibleRepo
    type: github
    endpoint: github.com_kgejara
    name: kgejara/AnsibleRepo
  - repository: TerraformRepo
    type: github
    endpoint: github.com_kgejara
    name: kgejara/TerraformRepo
    
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: AnsibleRepo
- checkout: TerraformRepo

- script: dir $(Build.SourcesDirectory)

- task: CopyFiles@2
  inputs:
    SourceFolder: 'ApplicationRepo/Code'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Code'
    OverWrite: true
    
- task: CopyFiles@2
  inputs:
    SourceFolder: 'AnsibleRepo/AnsibleScripts'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/AnsibleScripts'
    OverWrite: true
    
- task: CopyFiles@2
  inputs:
    SourceFolder: 'TerraformRepo/terraform-aws'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/terraform-aws'
    OverWrite: true
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
