resources:
  repositories:
  - repository: AnsibleRepo
    type: github
    endpoint: github.com_kgejara
    name: kgejara/AnsibleRepo
  - repository: TerraformRepo
    type: github
    endpoint: github.com_kgejara
    name: kgejara/TerraformRepo
  - repository: ApplicationRepo
    type: github
    endpoint: github.com_kgejara
    name: kgejara/ApplicationRepo
    
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: TerraformRepo
- checkout: AnsibleRepo
- checkout: ApplicationRepo

- script: dir $(Build.SourcesDirectory)

- task: CopyFiles@2
  inputs:
    SourceFolder: 'ApplicationRepo'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/ApplicationRepo'
    OverWrite: true
    
- task: CopyFiles@2
  inputs:
    SourceFolder: 'AnsibleRepo'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/AnsibleRepo'
    OverWrite: true
    
- task: CopyFiles@2
  inputs:
    SourceFolder: 'TerraformRepo'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/TerraformRepo'
    OverWrite: true
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform 0.12.24'
  inputs:
    terraformVersion: 0.12.24

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform Init - AWS'
  inputs:
    provider: aws
    workingDirectory: '$(System.DefaultWorkingDirectory)/_TerraformRepo_CI/drop/TerraformRepo/terraform-modules'
    backendServiceAWS: AWSTerraformServiceConnection
    backendAWSBucketName: terraformsremotestate123
    backendAWSKey: terraform.tfstate

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform Plan'
  inputs:
    provider: aws
    command: plan
    workingDirectory: '$(System.DefaultWorkingDirectory)/_TerraformRepo_CI/drop/TerraformRepo/terraform-modules'
    environmentServiceNameAWS: AWSTerraformServiceConnection
    backendServiceAWS: AWSTerraformServiceConnection
    backendAWSBucketName: terraformsremotestate123
    backendAWSKey: terrafor.state

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform Validate'
  inputs:
    provider: aws
    command: validate
    workingDirectory: '$(System.DefaultWorkingDirectory)/_TerraformRepo_CI/drop/TerraformRepo/terraform-modules'
    backendServiceAWS: AWSTerraformServiceConnection
    backendAWSBucketName: terraformsremotestate123
    backendAWSKey: terrafor.state

- task: GitHubComment@0
  displayName: 'Writing GitHub comment'
  inputs:
    gitHubConnection: 'github.com_kgejara'
    comment: 'Successfully Terraform Scripts Validated for PR'


